//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudOperation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Data
    {
        public int Sid { get; set; }
        public string Sname { get; set; }
        public string Department { get; set; }
        public string Addres { get; set; }
        public Nullable<int> DeptId { get; set; }
    
        public virtual tbl_Dept tbl_Dept { get; set; }
    }
}
